apiVersion: apps/v1
kind: Deployment
metadata:
  name: femibuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: femibuggy
  template:
    metadata:
      labels:
        app: femibuggy
    spec:
      containers:
      - name: femibuggy
        image: 595675427063.dkr.ecr.us-east-1.amazonaws.com/femisg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: femibuggy
    k8s-app: femibuggy
  name: femibuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: femibuggy
